# Generated by Django 2.0.7 on 2018-08-08 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=24, verbose_name='Категория клиента')),
                ('discount', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Категория клиента',
                'verbose_name_plural': 'Категории клиентов',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=128, verbose_name='Имя')),
                ('phone', models.CharField(default='+375', max_length=15, verbose_name='Телефон')),
                ('spare_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Доп. телефон')),
                ('address_delivery', models.TextField(default='Уточнять при заказе', max_length=128, verbose_name='Адрес доставки')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('short_description', models.TextField(blank=True, default=None, max_length=128, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Категория клиента', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Category')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
