# Generated by Django 2.0.7 on 2018-08-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180812_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Категория клиента',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_list', to='landing.Category'),
        ),
    ]
