# Generated by Django 2.0.7 on 2018-08-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20180813_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spare_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Доп. телефон'),
        ),
    ]
