# Generated by Django 2.0.7 on 2018-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20180817_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_description',
            field=models.TextField(blank=True, max_length=128, verbose_name='Дополнительная информация'),
        ),
    ]
