# Generated by Django 2.0.7 on 2018-08-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180816_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmanufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
    ]
