# Generated by Django 2.0.7 on 2018-08-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180816_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='артикл', max_length=7),
        ),
    ]
