# Generated by Django 2.0.7 on 2018-08-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(default='артикул', max_length=7),
        ),
    ]
