# Generated by Django 2.0.7 on 2018-08-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180816_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmanufacturer',
            old_name='fabric_name',
            new_name='name',
        ),
    ]
