# Generated by Django 2.0.7 on 2018-08-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180818_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={'verbose_name': 'Фабрика', 'verbose_name_plural': 'Фабрики'},
        ),
        migrations.AddField(
            model_name='fabric',
            name='short_description',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
