# Generated by Django 2.0.7 on 2018-08-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180818_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
