# Generated by Django 2.0.7 on 2018-08-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180818_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='ProductManufacturer',
        ),
    ]
