# Generated by Django 2.0.7 on 2018-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180824_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(default='артикул', max_length=7, unique=True),
        ),
    ]
