# Generated by Django 2.0.7 on 2018-08-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180825_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='prod_active',
        ),
    ]
